#!/usr/bin/sh

export HOMEX_TOKEN="0000"
export HOMEX_CONFIG="$(pwd)/homex.dev.toml"
cargo leptos watch --split --hot-reload

# To reset the dev DB after a model change:
#   HOMEX_RESET_SCHEMA=1 ./run
